### ISSUE TITLE
[German] Some questions only work in Simulator

### ISSUE THREAD

**Issue by PJF16** [tartanguru/alexa-google-search#7]
Hey!

I noticed, that in the simulator there nearly work all questions. But when I use the Echo, there are only a few questions that work. For example when I ask for the height of the Großglockner (the mountain in Austria) the simulator tells the right answer. Alexa says, that she couldn't finde the result.

What's the problem here?

EDIT:
I might found the reason. Alexa doesn't interpret some words after "ask google" like "how" (I also can see that in the Alexa App in the history). When I say "Alexa, ask google" and then wait until Alexa asks what to search for, it works. 

Any way to fix this?

**Comment by tartanguru** [comment]
I'm assuming that your are asking these questions in German and not English? It might be that the custom slot values are in English. Are you able to replace these with the German versions?

Such as:-

Wer die Königin ist

Warum ist der Himmel blau

**Comment by PJF16** [comment]
I thought of that. I will try it.

Am I right, if I assume, that if I add more slot values, the results are getting better?

**Comment by tartanguru** [comment]
Hi. I'm not sure I can add any more advice as I'm not a German speaker so can't really test this. The language translation is completely down to amazon.

My only other suggestion is to add some "how" type questions to the slot values so that it recognises the word. Also try asking some how questions to Alexa without using the skill. This will allow her to improve your voice model. If she gets the words wrong then go into the setting and find the item and click no on the "Did I hear you correctly?" option

**Comment by PJF16** [comment]
I did this all already. 

Maybe it's just a bug in the Voice Recognition service.

**Comment by ersguterjunge1911** [comment]
Hello! Is the skill working in german. With the short waiting time after saying ask google? Do you say ask google or frag google? Würde es gerne testen. Bin mir nicht sicher welche Teile auf deutch übersetzt werden sollen. Not really sure which parts wants to be translated in english. Thanks for answers and help

**Comment by tartanguru** [comment]
Hi, the skill is working is working in German and has translations for all of the voice elements. As long as you set up the skill to use German as the language and your device is set to german then it should work. I'm not a German speaker so I don't know the phrase in German for launching the skill.

**Comment by ersguterjunge1911** [comment]
Ok. Thank you for your fast response! I'll try the skill tonight

**Comment by PJF16** [comment]
To activate you just have to say "Alexa, frage Google [your question here]" ("Alexa, ask Google...").

@tartanguru I found something very curious: If you activate the skill in German with "Alexa, sage Google" (which means "Alexa, say Google [question]" in English) the "How?" questions are working in German. When you say "Alexa, ask Google [question]" in German, the "How?" questions aren't working.

**Comment by Luftloch80** [comment]
I think the google search is somehow different in german 
Why does an airplane fly works 
Warum fliegt ein Flugzeug does not work
and there are a lot more examples

**Comment by PJF16** [comment]
I can't agree with you. These questions work like a charm for me.

**Comment by ersguterjunge1911** [comment]
Kann  mir bitte jemand sagen, was ihr genau bei den Fragen eingeben habt? In Deutsch? Wenn ich wer ist die Königin schreiben möchte, bekomme ich die Meldung, wer was not found in the domain definition. Danke für jede Information

**Comment by ersguterjunge1911** [comment]
Habs hinbekommen, Danke! Muss nur noch die beste Art der Fragestellung rausbekommen

**Comment by ersguterjunge1911** [comment]
How do you create the sentence? Alexa frag google warum fliegt ein Flugzeug works for me. I think it is really Important how you ask the question. Maybe anyone has an idea?

**Comment by tartanguru** [comment]
Hi everyone - I have no way of testing the skill in German as I am not a German speaker, but I am happy to help if you are able to test some alternative google search strings.

The skill sends a search to google.de with the language set to German as well. 
Can someone try try the skill with a different language setting to see if that makes a difference by changing this line in index.js to one of the two  following and let me know whether they make any difference please:-

Change:-
    var localeGoogleDE = ["http://www.google.com/search?q=", "&hl=de"];
to:-
    var localeGoogleDE = ["http://www.google.de/search?q=", ""];
(this might not work as the server is in Ireland and might use google.de but default to English)

or alternatively to:-
    var localeGoogleDE = ["http://www.google.de/search?q=", "&hl=de"];
(this should force German as the language)

If it works in the simulator and not on the actual Echo device then the issue lies in the Amazon text to speech engine which I have no control over.

Note - one other German user has reported that the skill works better if you call the skill Gugl as this is apparently closer to the German pronunciation

Thanks

**Comment by tartanguru** [comment]
I haven't received any feedback on this. If I don't receive any in the next few days then I will close this issue

**Comment by ersguterjunge1911** [comment]
I think it it is no issue anymore. The skill works, like it schould.

**Comment by likeadoc** [comment]
Still the same problem as @PJF16  pointed out -> "I found something very curious: If you activate the skill in German with "Alexa, sage Google" (which means "Alexa, say Google [question]" in English) the "How?" questions are working in German. When you say "Alexa, ask Google [question]" in German, the "How?" questions aren't working."

![testgoogle](https://cloud.githubusercontent.com/assets/16107593/22628116/aaec2b22-ebce-11e6-93ba-d96af395d3cc.png)

**Comment by likeadoc** [comment]
the funny thing is if you say " frage google nach: wie hoch ist der mount everest" which translates roughly to "ask google about: how high is the mount everest ?" it works like a charm

**Comment by likeadoc** [comment]
changing var localeGoogleDE didnt do a thing - it seems like Alexas german TTS doesnt recognize the "wie " (how) after "Frage Google" (ask google)

**Comment by likeadoc** [comment]
also saying "frage google, wie wie hoch ist der mount everest" (ask google, how how high is mount everest) works!

**Comment by likeadoc** [comment]
if you use the simulator and type in "frag google wie hoch ist der mount everest" (ask google how high is mount everest" the "wie"(how) gets cut off in the service request. If you just type "wie hoch ist der mount everest" (how high is mount everest) (without ask google) everything works as expected!

**Comment by tartanguru** [comment]
Ok - thanks for the extra information. I think this is an issue with the Amazon speech to text in German which I can't do anything about, so I'm going to close this issue
